import { readFile } from "node:fs/promises";
import { dirname, extname, resolve, sep } from "node:path";
import { Glob } from "bun";
import { compile } from "tailwindcss";
import type { ConnectNodeAdapterOptions } from "@connectrpc/connect-node";

// connect-node does not export NodeHandlerFn/NodeServerRequest/NodeServerResponse from its
// package root - only ConnectNodeAdapterOptions, whose `fallback` field they name. Deriving
// them from it (rather than typing this handler against plain node:http, which the admin
// server happens to use today) keeps this assignable to `fallback` even if that ever grows
// to cover the h2c control listener too.
type NodeHandlerFn = NonNullable<ConnectNodeAdapterOptions["fallback"]>;
type NodeServerRequest = Parameters<NodeHandlerFn>[0];
type NodeServerResponse = Parameters<NodeHandlerFn>[1];

const CONTENT_TYPES: Record<string, string> = {
	".html": "text/html; charset=utf-8",
	".css": "text/css; charset=utf-8",
	".js": "text/javascript; charset=utf-8",
};

function contentTypeFor(path: string): string {
	return CONTENT_TYPES[extname(path)] ?? "application/octet-stream";
}

/**
 * Resolves a request path to a file under `webRoot`, or `null` if it escapes `webRoot`
 * (`../../etc/passwd`, an encoded `%2e%2e`, ...) or isn't one of the extensions this
 * dashboard actually ships (blocks `/main.tsx` - the source, not the bundle - from being
 * served as-is). `/main.js` and `/style.css` never reach here: they are generated by
 * `bundleMain`/`bundleCss`, not files read from `webRoot`, and the caller intercepts both
 * first - `.css` staying in `CONTENT_TYPES` would otherwise let the uncompiled source
 * `style.css` be served in place of the compiled one.
 */
export function resolveStaticPath(webRoot: string, requestPath: string): string | null {
	const pathname = requestPath.split("?")[0] || "/";
	let decoded: string;
	try {
		decoded = decodeURIComponent(pathname);
	} catch {
		return null;
	}

	const relative = decoded === "/" ? "index.html" : decoded.slice(1);
	const resolvedRoot = resolve(webRoot);
	const resolved = resolve(resolvedRoot, relative);
	const rootWithSep = resolvedRoot.endsWith(sep) ? resolvedRoot : resolvedRoot + sep;
	if (resolved !== resolvedRoot && !resolved.startsWith(rootWithSep)) return null;
	if (!(extname(resolved) in CONTENT_TYPES)) return null;
	return resolved;
}

/**
 * Bundles the dashboard's browser entrypoint once, at server start rather than as a
 * separate build step. This is an internal tool run with `bun server/bin/app.ts` - there is
 * no install/build/run pipeline to slot a build step into, and a stale dist/ committed or
 * gitignored is one more thing to get wrong. The cost is paid once at boot (a few hundred
 * ms), not per request.
 */
export async function bundleMain(webRoot: string): Promise<string> {
	const result = await Bun.build({
		entrypoints: [resolve(webRoot, "main.tsx")],
		target: "browser",
		format: "esm",
	});
	if (!result.success) {
		const messages = result.logs.map((log) => log.message).join("\n");
		throw new Error(`failed to bundle server/web/main.tsx:\n${messages}`);
	}
	const [output] = result.outputs;
	if (!output) throw new Error("Bun.build produced no output for server/web/main.tsx");
	return output.text();
}

/**
 * Splits source into string-literal bodies, skipping comments. A regex over the whole file
 * cannot do this: it pairs quote characters wherever they fall, so a single apostrophe in a
 * prose comment ("the panel's background") opens a literal that closes on the next unrelated
 * quote, and every real class list after it is read as comment and dropped. That failure is
 * silent - the page simply loses styles from that point down - so the scan tracks what it is
 * inside of instead of pattern-matching quotes.
 */
function extractStringLiterals(text: string): string[] {
	const literals: string[] = [];
	let i = 0;
	while (i < text.length) {
		const c = text[i]!;
		if (c === "/" && text[i + 1] === "/") {
			i = text.indexOf("\n", i);
			if (i === -1) break;
		} else if (c === "/" && text[i + 1] === "*") {
			const end = text.indexOf("*/", i + 2);
			i = end === -1 ? text.length : end + 2;
		} else if (c === '"' || c === "'" || c === "`") {
			let j = i + 1;
			while (j < text.length && text[j] !== c) j += text[j] === "\\" ? 2 : 1;
			literals.push(text.slice(i + 1, j));
			i = j + 1;
		} else {
			i += 1;
		}
	}
	return literals;
}

/**
 * Stands in for the Oxide `Scanner` a real Tailwind build integration (Vite, PostCSS) would
 * use - `@tailwindcss/oxide` isn't installed (see task-0-report.md). Candidates only ever
 * live inside a source file's string/template literals, so this splits each literal body on
 * whitespace (the actual boundary between class names in a class list) rather than matching
 * "class-name-shaped" characters against the whole file - the latter swallows the literal's
 * own closing quote into the last candidate (`...)]"`, which then fails to compile) whenever
 * a class list ends a string with no trailing space. `compile().build()` silently drops any
 * candidate that isn't a valid utility, so the stray tokens a template literal's `${...}`
 * interpolation leaves behind are harmless.
 */
export async function scanClassCandidates(webRoot: string): Promise<string[]> {
	const candidates = new Set<string>();
	const glob = new Glob("**/*.{ts,tsx,html}");
	for await (const file of glob.scan({ cwd: webRoot, absolute: true })) {
		if (file.endsWith(".test.ts") || file.endsWith(".test.tsx")) continue;
		for (const literal of extractStringLiterals(await readFile(file, "utf8"))) {
			for (const token of literal.split(/[\s`${}]+/)) {
				if (token) candidates.add(token);
			}
		}
	}
	return [...candidates];
}

/**
 * Compiles `style.css` with Tailwind v4's programmatic `compile()`, not `bun-plugin-tailwind`
 * - the plugin bundles its own frozen Tailwind engine (v4.1.14) instead of the installed
 * `tailwindcss` package, so bumping the package would silently do nothing (task-0-report.md).
 * `compile()` has no built-in module resolution, so `loadStylesheet` special-cases the bare
 * `"tailwindcss"` id: Bun's resolver follows the "import" condition to the JS entrypoint, not
 * the "style" condition bundlers use for `@import "tailwindcss"`, so this anchors on the
 * package's own package.json and takes the sibling index.css directly.
 */
export async function bundleCss(webRoot: string): Promise<string> {
	const cssPath = resolve(webRoot, "style.css");
	const source = await readFile(cssPath, "utf8");
	const compiler = await compile(source, {
		base: webRoot,
		loadStylesheet: async (id, base) => {
			const path =
				id === "tailwindcss"
					? resolve(dirname(Bun.resolveSync("tailwindcss/package.json", base)), "index.css")
					: Bun.resolveSync(id, base);
			const content = await readFile(path, "utf8");
			return { path, base: dirname(path), content };
		},
	});
	const candidates = await scanClassCandidates(webRoot);
	return compiler.build(candidates);
}

export type DashboardHandlerOptions = { webRoot: string; bundleJs: string; bundleCss: string };

/**
 * The admin listener's `connectNodeAdapter` fallback: anything that isn't a recognised
 * Connect/gRPC-Web route lands here. Serves the dashboard's static files plus the bundled
 * `/main.js` and `/style.css` from memory - there is no separate router or third port, per
 * the plan.
 */
export function newDashboardFallback(opts: DashboardHandlerOptions): NodeHandlerFn {
	return (req, res) => {
		void serve(req, res, opts).catch((err: unknown) => {
			console.error("[raven-server] dashboard static handler error:", err);
			if (!res.headersSent) {
				res.writeHead(500);
				res.end("internal error");
			}
		});
	};
}

async function serve(req: NodeServerRequest, res: NodeServerResponse, opts: DashboardHandlerOptions): Promise<void> {
	const pathname = (req.url ?? "/").split("?")[0] || "/";

	if (pathname === "/main.js") {
		res.writeHead(200, { "content-type": contentTypeFor("main.js") });
		res.end(opts.bundleJs);
		return;
	}

	if (pathname === "/style.css") {
		res.writeHead(200, { "content-type": contentTypeFor("style.css") });
		res.end(opts.bundleCss);
		return;
	}

	const filePath = resolveStaticPath(opts.webRoot, pathname);
	if (!filePath) {
		res.writeHead(404);
		res.end("not found");
		return;
	}

	try {
		const body = await readFile(filePath);
		res.writeHead(200, { "content-type": contentTypeFor(filePath) });
		res.end(body);
	} catch {
		res.writeHead(404);
		res.end("not found");
	}
}
