import { readFile } from "node:fs/promises";
import { extname, resolve, sep } from "node:path";
import type { ConnectNodeAdapterOptions } from "@connectrpc/connect-node";

// connect-node does not export NodeHandlerFn/NodeServerRequest/NodeServerResponse from its
// package root - only ConnectNodeAdapterOptions, whose `fallback` field they name. Deriving
// them from it (rather than typing this handler against plain node:http, which the admin
// server happens to use today) keeps this assignable to `fallback` even if that ever grows
// to cover the h2c control listener too.
type NodeHandlerFn = NonNullable<ConnectNodeAdapterOptions["fallback"]>;
type NodeServerRequest = Parameters<NodeHandlerFn>[0];
type NodeServerResponse = Parameters<NodeHandlerFn>[1];

const CONTENT_TYPES: Record<string, string> = {
	".html": "text/html; charset=utf-8",
	".css": "text/css; charset=utf-8",
	".js": "text/javascript; charset=utf-8",
};

function contentTypeFor(path: string): string {
	return CONTENT_TYPES[extname(path)] ?? "application/octet-stream";
}

/**
 * Resolves a request path to a file under `webRoot`, or `null` if it escapes `webRoot`
 * (`../../etc/passwd`, an encoded `%2e%2e`, ...) or isn't one of the extensions this
 * dashboard actually ships (blocks `/main.ts` - the source, not the bundle - from being
 * served as-is). `/main.js` never reaches here: it is generated by `bundleMain`, not a file
 * that exists under `webRoot`, and the caller intercepts it first.
 */
export function resolveStaticPath(webRoot: string, requestPath: string): string | null {
	const pathname = requestPath.split("?")[0] || "/";
	let decoded: string;
	try {
		decoded = decodeURIComponent(pathname);
	} catch {
		return null;
	}

	const relative = decoded === "/" ? "index.html" : decoded.slice(1);
	const resolvedRoot = resolve(webRoot);
	const resolved = resolve(resolvedRoot, relative);
	const rootWithSep = resolvedRoot.endsWith(sep) ? resolvedRoot : resolvedRoot + sep;
	if (resolved !== resolvedRoot && !resolved.startsWith(rootWithSep)) return null;
	if (!(extname(resolved) in CONTENT_TYPES)) return null;
	return resolved;
}

/**
 * Bundles the dashboard's browser entrypoint once, at server start rather than as a
 * separate build step. This is an internal tool run with `bun server/bin/app.ts` - there is
 * no install/build/run pipeline to slot a build step into, and a stale dist/ committed or
 * gitignored is one more thing to get wrong. The cost is paid once at boot (a few hundred
 * ms), not per request.
 */
export async function bundleMain(webRoot: string): Promise<string> {
	const result = await Bun.build({
		entrypoints: [resolve(webRoot, "main.ts")],
		target: "browser",
		format: "esm",
	});
	if (!result.success) {
		const messages = result.logs.map((log) => log.message).join("\n");
		throw new Error(`failed to bundle server/web/main.ts:\n${messages}`);
	}
	const [output] = result.outputs;
	if (!output) throw new Error("Bun.build produced no output for server/web/main.ts");
	return output.text();
}

export type DashboardHandlerOptions = { webRoot: string; bundleJs: string };

/**
 * The admin listener's `connectNodeAdapter` fallback: anything that isn't a recognised
 * Connect/gRPC-Web route lands here. Serves the dashboard's static files plus the bundled
 * `/main.js` from memory - there is no separate router or third port, per the plan.
 */
export function newDashboardFallback(opts: DashboardHandlerOptions): NodeHandlerFn {
	return (req, res) => {
		void serve(req, res, opts).catch((err: unknown) => {
			console.error("[raven-server] dashboard static handler error:", err);
			if (!res.headersSent) {
				res.writeHead(500);
				res.end("internal error");
			}
		});
	};
}

async function serve(req: NodeServerRequest, res: NodeServerResponse, opts: DashboardHandlerOptions): Promise<void> {
	const pathname = (req.url ?? "/").split("?")[0] || "/";

	if (pathname === "/main.js") {
		res.writeHead(200, { "content-type": contentTypeFor("main.js") });
		res.end(opts.bundleJs);
		return;
	}

	const filePath = resolveStaticPath(opts.webRoot, pathname);
	if (!filePath) {
		res.writeHead(404);
		res.end("not found");
		return;
	}

	try {
		const body = await readFile(filePath);
		res.writeHead(200, { "content-type": contentTypeFor(filePath) });
		res.end(body);
	} catch {
		res.writeHead(404);
		res.end("not found");
	}
}
