name: Build And Release

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - run: yarn
    - name: Build
      run: yarn build -p onTag
    - name: Upload ${{ matrix.os }} build
      uses: actions/upload-artifact@v3
      with:
        name: builds-${{ matrix.os }}
        path: dist/**
