name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - run: yarn
    - name: Build
      run: yarn build
    - name: Upload ${{ matrix.os }} build
      uses: actions/upload-artifact@v3
      with:
        name: builds-${{ matrix.os }}
        path: build/**